import { useState } from 'react';
import Head from 'next/head';
import { FaGithub, FaTimes } from 'react-icons/fa';

import styles from './styles.module.scss';

import { BrandDefault } from '../BrandDefault';
import { IHeaderDsMovie } from './IHeaderDsMovie';
import { ButtonDefault } from '../ButtonDefault';

const HeaderDsMovie: React.FC<IHeaderDsMovie> = ({ title }) => {
  const [isLogin, setIsLogin] = useState(false);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <div className={`container ${styles.header__container}`}>
          <div className='content grid grid_2'>
            <BrandDefault href='/' type='brand-text' title='DSMovie' />
            {/* <NavDefault type='nav-hozontal' /> */}
            {isLogin ? (
              <div className={`${styles.header__container_perfil}`}>
                <ButtonDefault size='small' type='button' title='Olá Matheus'>
                  <FaTimes width={32} height={32} />
                </ButtonDefault>
              </div>
            ) : (
              <ButtonDefault
                size='small'
                type='button'
                title='Entrar com github'
                className='dflex '
              >
                <FaGithub width={32} height={32} />
              </ButtonDefault>
            )}
          </div>
        </div>
      </header>
    </>
  );
};

export { HeaderDsMovie };
