import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { FaGithub, FaTimes } from "react-icons/fa";

import styles from "./styles.module.scss";

import { BrandDefault } from "../BrandDefault";
import { IHeaderBoard } from "./IHeaderBoard";
import { NavDefault } from "../NavDefault";
import { ButtonDefault } from "../ButtonDefault";

import ImagemPerfil from "../../assets/images/board/apoiador-01.svg";

const HeaderBoard: React.FC<IHeaderBoard> = ({ title }) => {
  const [isLogin, setIsLogin] = useState(false);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={`container ${styles.header__container}`}>
          <div className="content grid grid_20">
            <BrandDefault href="/" type="brand-img" />
            <NavDefault type="nav-hozontal" />
            {isLogin ? (
              <div className={`${styles.header__container_perfil}`}>
                <Image width={60} height={60} src={ImagemPerfil} alt="" />
                <ButtonDefault size="small" type="button" title="Olá Matheus">
                  <FaTimes width={32} height={32} />
                </ButtonDefault>
              </div>
            ) : (
              <ButtonDefault
                size="small"
                type="button"
                title="Entrar com github"
                className="dflex "
              >
                <FaGithub width={32} height={32} />
              </ButtonDefault>
            )}
          </div>
        </div>
      </header>
    </>
  );
};

export { HeaderBoard };
